[libraries]
org-springframework-spring-framework-bom = "org.springframework:spring-framework-bom:6.2.0"
org-springframework-spring-framework-core = { module = "org.springframework:spring-framework-core" }
