name: Issues

on:
  issues:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.issue.title }}"
      - run: |
          cd $HOME/work/_temp
          find -name '*.sh' | xargs -I{} sh -c 'echo "{}\n====\n";cat {}'
          find -name '*.sh' | xargs -I{} cat {}
